name:                horrelate
version:             0.1.0.0
github:              "githubuser/horrelate"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/horrelate#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - dear-imgui
  - gl
  - sdl2
  - aeson >= 1.5.5.1
  - listsafe
  - errors >= 2.3.0
  - mtl >= 2.2.2
  - bytestring >= 0.10.12.0
  - generic-lens >= 2.0.0.0
  - lens >= 4.19.2

executables:
  horrelate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - horrelate
    - dear-imgui
    - vulkan
    - vulkan-utils
    - gl
    - sdl2
    - managed
    - mtl >= 2.2.2
    - lens >= 4.19.2

tests:
  horrelate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - horrelate
